library(sprex)
temp = list.files(pattern="*DCurve.csv")
for (i in 1:length(temp)) assign(temp[i], read.csv(temp[i],sep=";"))
Crete <- expand.freqs(Crete_DCurve.csv)
Crete_curve <- discovery.curve(Crete, f0.func = iChao1, max.x=15000,n.pts=300)
Samos <- expand.freqs(Samos_DCurve.csv)
Samos_curve <- discovery.curve(Samos, f0.func = iChao1, max.x=15000,n.pts=300)
Rhodes <- expand.freqs(Rhodes_DCurve.csv)
Rhodes_curve <- discovery.curve(Rhodes, f0.func = iChao1, max.x=15000,n.pts=300)
Chios <- expand.freqs(Chios_DCurve.csv)
Chios_curve <- discovery.curve(Chios, f0.func = iChao1, max.x=15000,n.pts=300)
Corfu <- expand.freqs(Corfu_DCurve.csv)
Corfu_curve <- discovery.curve(Corfu, f0.func = iChao1, max.x=15000,n.pts=300)
Kos <- expand.freqs(Kos_DCurve.csv)
Kos_curve <- discovery.curve(Kos, f0.func = iChao1, max.x=15000,n.pts=300)
Ikaria <- expand.freqs(Ikaria_DCurve.csv)
Ikaria_curve <- discovery.curve(Ikaria, f0.func = iChao1, max.x=15000,n.pts=300)
Lesbos <- expand.freqs(Lesbos_DCurve.csv)
Lesbos_curve <- discovery.curve(Lesbos, f0.func = iChao1, max.x=15000,n.pts=300)
Skyros <- expand.freqs(Skyros_DCurve.csv)
Skyros_curve <- discovery.curve(Skyros, f0.func = iChao1, max.x=15000,n.pts=300)
Karpathos <- expand.freqs(Karpathos_DCurve.csv)
Karpathos_curve <- discovery.curve(Karpathos, f0.func = iChao1, max.x=15000,n.pts=300)
#plot(Samos_curve,  pch=21, lty=1, col = "#d3d3d3")
#plot(Ikaria_curve, col = "#ffd1dc", add = TRUE, pch=23, lty=3)
#plot(Crete_curve, col = "#afeeee", add = TRUE, pch=22, lty=2)
#plot(Chios_curve, col = "#f5f5dc", add = TRUE)
legend(1, 300, c("Samos", "Crete", "Ikaria"), cex=0.8, col=c("#d3d3d3","#afeeee","#ffd1dc"),pch=21:23,lty=1:3)