require(sprex)
require(svMisc)
setwd("C:/Users/eranee/Desktop/Beetles")
temp = list.files(pattern="*DCurve.csv")
for (i in 1:length(temp)) assign(temp[i], read.csv(temp[i],sep=";"))
oldw <- getOption("warn")
options(warn = -1)
rm(i,x,y,z,d,Location, MV)
temp = as.character(objects(pattern=".csv"))
options(warn = oldw)
for (i in seq_along(temp)){
  #progress(i, progress.bar = TRUE)
  x <- get(temp[i])
  y <- expand.freqs(x)
  z <- deparse(temp[i])
  Location <- str_remove(z,"_DCurve.csv")
  Location <- paste(str_remove_all(Location,"\""), "_curve", sep="")
  print(Location)
  d <- discovery.curve(y, f0.func = ACE, max.x=10000,n.pts=200)
  assign(Location,d)
}
#Crete <- expand.freqs(Crete_DCurve.csv)
#Crete_curve <- discovery.curve(Crete, f0.func = ACE, max.x=10000,n.pts=200)
#Samos <- expand.freqs(Samos_DCurve.csv)
#Samos_curve <- discovery.curve(Samos, f0.func = ACE, max.x=10000,n.pts=200)
#Rhodes <- expand.freqs(Rhodes_DCurve.csv)
#Rhodes_curve <- discovery.curve(Rhodes, f0.func = ACE, max.x=10000,n.pts=200)
#Chios <- expand.freqs(Chios_DCurve.csv)
#Chios_curve <- discovery.curve(Chios, f0.func = ACE, max.x=10000,n.pts=200)
#Corfu <- expand.freqs(Corfu_DCurve.csv)
#Corfu_curve <- discovery.curve(Corfu, f0.func = ACE, max.x=15000,n.pts=300)
#Kos <- expand.freqs(Kos_DCurve.csv)
#Kos_curve <- discovery.curve(Kos, f0.func = ACE, max.x=10000,n.pts=200)
#Ikaria <- expand.freqs(Ikaria_DCurve.csv)
#Ikaria_curve <- discovery.curve(Ikaria, f0.func = ACE, max.x=10000,n.pts=200)
#Lesbos <- expand.freqs(Lesbos_DCurve.csv)
#Lesbos_curve <- discovery.curve(Lesbos, f0.func = ACE, max.x=10000,n.pts=200)
#Skyros <- expand.freqs(Skyros_DCurve.csv)
#Skyros_curve <- discovery.curve(Skyros, f0.func = ACE, max.x=10000,n.pts=200)
#Karpathos <- expand.freqs(Karpathos_DCurve.csv)
#Karpathos_curve <- discovery.curve(Karpathos, f0.func = ACE, max.x=10000,n.pts=200)
#Samothraki <- expand.freqs(Samothraki_DCurve.csv)
#Samothraki_curve <- discovery.curve(Samothraki,f0.func = ACE, max.x=10000, n.pts=200)
#plot(Samos_curve,  pch=21, lty=1, col = "#d3d3d3")
#plot(Ikaria_curve, col = "#ffd1dc", add = TRUE, pch=23, lty=3)
#plot(Crete_curve, col = "#afeeee", add = TRUE, pch=22, lty=2)
#plot(Chios_curve, col = "#f5f5dc", add = TRUE)